version: '3.8'
services:
  postgres_restaurant:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_restaurant:/var/lib/postgresql/data
    ports:
      - '6543:5432'
volumes:
  postgres_restaurant: